# Generated by Django 4.2.7 on 2023-11-14 03:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='value',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=255, null=True),
        ),
    ]
