# Generated by Django 4.2.7 on 2023-11-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_token_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='auto_subscribe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='token',
            name='inherit_subscriptions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='token',
            name='max_connections',
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
    ]
