# Generated by Django 4.2.7 on 2023-11-14 23:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0003_token_auto_subscribe_token_inherit_subscriptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='slug',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=255, null=True),
        ),
    ]
